steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["clean"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospring", "--build-arg=JAR_FILE=target/spring-boot-initial-0.0.1.jar", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/hellospring"]
  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=kubernetes.yaml
    - --image=gcr.io/$PROJECT_ID/hellospring
    - --location=uscentral-1c
    - --cluster=gyi-cluster
options:
    logging: CLOUD_LOGGING_ONLY